### ISSUE TITLE
Back to first page when choose any filter or sort

### ISSUE THREAD

**Issue by DanielSuhett** [stephannv/nindika#160]
Hello, i would like to suggest back to first page when make new filter or sort

**Comment by stephannv** [comment]
Thanks @DanielSuhett for the suggestion. I will add this behavior to the next release (coming in few days).

**Comment by stephannv** [comment]
I'm closing this issue @DanielSuhett . The lastest release should solve this problem. If the problem persists, please, reopen this issue.
